//
// See doc/LICENSE.md for license terms
//

#ifndef YGG_TESTS_COMMON_LOGGING_LOGGING_TESTS_H_INCLUDED
#define YGG_TESTS_COMMON_LOGGING_LOGGING_TESTS_H_INCLUDED

void LoggingTests_TestSuite();

#endif /* YGG_TESTS_COMMON_LOGGING_LOGGING_TESTS_H_INCLUDED */
