//
// See doc/LICENSE.md for license terms
//

#ifndef YGG_TESTS_COMMON_THREADING_LOCK_TESTS_H_INCLUDED
#define YGG_TESTS_COMMON_THREADING_LOCK_TESTS_H_INCLUDED

void LockTests_TestSuite();

#endif /* YGG_TESTS_COMMON_THREADING_LOCK_TESTS_H_INCLUDED */
